name: CI

on:
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc librtlsdr-dev libbluetooth-dev

    - name: Build
      run: |
        make

    - name: Clean up
      run: |
        make clean
